[package]

name = "backbonzo"
version = "0.2.5"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
docopt = "*"
docopt_macros = "*"
time = "*"
glob = "*"
rustc-serialize = "*"

[dependencies.rust-crypto]
git = "https://github.com/dagenix/rust-crypto"

[dependencies.rusqlite]
git = "https://github.com/jgallagher/rusqlite"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

