[package]
name = "backbonzo"
version = "0.4.9"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
glob = "*"
rustc-serialize = "*"
rusqlite = "*"
libsqlite3-sys = "*"
rust-crypto = "*"
rand = "*"
regex = "*"
docopt = "*"
tempdir = "*"
time = "*"
termios = "*"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs.git"

[dependencies.number_prefix]
git = "https://github.com/ogham/rust-number-prefix.git"

[dependencies.comm]
git = "https://github.com/mahkoh/comm"

[dependencies.iter-reduce]
git = "https://github.com/marcusklaas/iter-reduce"

[[bin]]
name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

