[package]

name = "backbonzo"
version = "0.2.1"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
rusqlite = "*"
docopt = "*"
docopt_macros = "*"
time = "*"
regex = "*"
rustc-serialize = "*"
rust-crypto = "*"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

