[package]

name = "backbonzo"
version = "0.1.0"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies.rusqlite]
git = "https://github.com/marcusklaas/rusqlite.git"
rev = "242d9469656e46d3b215ecc222dd34256c705b83"

[dependencies]
docopt = "*"
docopt_macros = "*"
rust-crypto = "*"
time = "*"

[[bin]]

name = "backbonzo"

