[package]

name = "backbonzo"
version = "0.2.8"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
docopt = "*"
time = "*"
glob = "*"
rustc-serialize = "*"
rusqlite = "*"
regex = "*" # for tests only -- shouldnt be linked in otherwise
regex_macros = "*"

[dependencies.rust-crypto]
git = "https://github.com/dagenix/rust-crypto"

[dependencies.spsc]
git = "https://github.com/marcusklaas/rust-spsc"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

