[package]

name = "backbonzo"
version = "0.2.0"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
rusqlite = "*"
docopt = "*"
docopt_macros = "*"
time = "*"
regex = "*"
rustc-serialize = "*"

[dependencies.rust-crypto]
git="https://github.com/marcusklaas/rust-crypto.git"

[[bin]]

name = "backbonzo"

