[package]

name = "backbonzo"
version = "0.3.1"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
time = "*"
glob = "*"
rustc-serialize = "*"
#rusqlite = "*"
#libsqlite3-sys = "*"
#rust-crypto = "*"
rand = "*"
regex = "*"
regex_macros = "*"
docopt = "*"
tempdir = "*"

[dependencies.rusqlite]
git = "https://github.com/marcusklaas/rusqlite.git"
rev = "f30ceffa6ca0d6a988675"

[dependencies.libsqlite3-sys]
git = "https://github.com/marcusklaas/rusqlite.git"
rev = "f30ceffa6ca0d6a988675"

[dependencies.rust-crypto]
git = "https://github.com/dagenix/rust-crypto.git"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs.git"

[dependencies.number_prefix]
git = "https://github.com/ogham/rust-number-prefix.git"

[dependencies.comm]
git = "https://github.com/mahkoh/comm"

[dependencies.iter-reduce]
git = "https://github.com/marcusklaas/iter-reduce"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

