[package]

name = "backbonzo"
version = "0.2.4"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
docopt = "*"
docopt_macros = "*"
time = "*"
glob = "*"
rustc-serialize = "*"

[dependencies.rust-crypto]
git = "https://github.com/fhartwig/rust-crypto"
rev = "4b20015bd62685863343ccac8c88684e98467a28"

[dependencies.bzip2]
git = "https://github.com/alexcrichton/bzip2-rs"

[dependencies.rusqlite]
git = "https://github.com/marcusklaas/rusqlite"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

