[package]

name = "backbonzo"
version = "0.0.2"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies.rusqlite]
rust-sqlite = "*"

[dependencies]
rust-crypto = "*"
time = "*"
docopt = "*"
docopt_macros = "*"

[[bin]]

name = "backbonzo"
