[package]

name = "backbonzo"
version = "0.2.17"
authors = ["Marcus Klaas <mail@marcusklaas.nl>"]

[lib]
name = "backbonzo"

[dependencies]
docopt = "*"
time = "*"
glob = "*"
rustc-serialize = "*"
rusqlite = "*"
libsqlite3-sys = "*"
rust-crypto = "*"
bzip2 = "*"
rand = "*"

[dependencies.regex]
git = "https://github.com/rust-lang/regex.git"

[dependencies.regex_macros]
git = "https://github.com/rust-lang/regex.git"

[dependencies.comm]
git = "https://github.com/mahkoh/comm"

[dependencies.iter-reduce]
git = "https://github.com/marcusklaas/iter-reduce"

[[bin]]

name = "backbonzo"

# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false

